version: '3.9'
services:
  backend:
    build: ./Backend
    container_name: backend-container
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
        
  frontend:
    build: ./Frontend
    container_name: frontend-container
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=development