version: '3.9'
services:
  backend:
    image: todolist-backend
    container_name: backend-container
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
  frontend:
    image: todolist-frontend
    container_name: frontend-container
    ports:
      - '5173:5173'